apiVersion: v2
type: application
version: 2.4.3
appVersion: "1.4.3"
name: pagopa-ecommerce-watchdog-deadletter-fe
description: Rect Typescript frontend application designed to support deadletter monitoring for the eCommerce transactions process.
dependencies:
  - name: microservice-chart
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    version: 8.0.0
